FROM golang:1.25 AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /bin/provider-openstack ./services/provider-openstack/cmd

FROM alpine:3.18
COPY --from=build /bin/provider-openstack /bin/provider-openstack
EXPOSE 50052
ENTRYPOINT ["/bin/provider-openstack"]
