FROM golang:1.25 AS build
WORKDIR /app

COPY . .
RUN go mod download

# Build static Linux binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/api-gateway ./services/api-gateway/cmd

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/api-gateway /bin/api-gateway
EXPOSE 8080
ENTRYPOINT ["/bin/api-gateway"]
