FROM golang:1.20-alpine AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /bin/provider-vmware ./services/provider-vmware/cmd

FROM alpine:3.18
COPY --from=build /bin/provider-vmware /bin/provider-vmware
EXPOSE 50051
ENTRYPOINT ["/bin/provider-vmware"]
