FROM golang:1.25 AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /bin/api-gateway ./services/api-gateway/cmd

FROM alpine:3.18
COPY --from=build /bin/api-gateway /bin/api-gateway
EXPOSE 8080
ENTRYPOINT ["/bin/api-gateway"]
