FROM golang:1.20-alpine AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /bin/orchestrator ./services/orchestrator/cmd

FROM alpine:3.18
COPY --from=build /bin/orchestrator /bin/orchestrator
EXPOSE 50060
ENTRYPOINT ["/bin/orchestrator"]
