FROM golang:1.25 AS build
WORKDIR /app

COPY . .
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/orchestrator ./services/orchestrator/cmd

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/orchestrator /bin/orchestrator
EXPOSE 50060
ENTRYPOINT ["/bin/orchestrator"]
