FROM golang:1.25 AS build
WORKDIR /app

COPY . .
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/provider-vmware ./services/provider-vmware/cmd

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/provider-vmware /bin/provider-vmware
EXPOSE 50051
ENTRYPOINT ["/bin/provider-vmware"]
