// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/vmmigrator.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_UNKNOWN   JobState = 0
	JobState_QUEUED    JobState = 1
	JobState_RUNNING   JobState = 2
	JobState_FAILED    JobState = 3
	JobState_COMPLETED JobState = 4
	JobState_CANCELLED JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "UNKNOWN",
		1: "QUEUED",
		2: "RUNNING",
		3: "FAILED",
		4: "COMPLETED",
		5: "CANCELLED",
	}
	JobState_value = map[string]int32{
		"UNKNOWN":   0,
		"QUEUED":    1,
		"RUNNING":   2,
		"FAILED":    3,
		"COMPLETED": 4,
		"CANCELLED": 5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vmmigrator_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_proto_vmmigrator_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{0}
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           int64                  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Disks         []*Disk                `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_proto_vmmigrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{0}
}

func (x *VMInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMInfo) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *VMInfo) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMInfo) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_proto_vmmigrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{1}
}

func (x *Disk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Disk) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Disk) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       map[string]string      `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_proto_vmmigrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{2}
}

func (x *ListVMsRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_proto_vmmigrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{3}
}

func (x *ListVMsResponse) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type ExportVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	StagingTarget string                 `protobuf:"bytes,2,opt,name=staging_target,json=stagingTarget,proto3" json:"staging_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportVMRequest) Reset() {
	*x = ExportVMRequest{}
	mi := &file_proto_vmmigrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportVMRequest) ProtoMessage() {}

func (x *ExportVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportVMRequest.ProtoReflect.Descriptor instead.
func (*ExportVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{4}
}

func (x *ExportVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ExportVMRequest) GetStagingTarget() string {
	if x != nil {
		return x.StagingTarget
	}
	return ""
}

type ExportVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportVMResponse) Reset() {
	*x = ExportVMResponse{}
	mi := &file_proto_vmmigrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportVMResponse) ProtoMessage() {}

func (x *ExportVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportVMResponse.ProtoReflect.Descriptor instead.
func (*ExportVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{5}
}

func (x *ExportVMResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ExportVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImportVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Opts          map[string]string      `protobuf:"bytes,2,rep,name=opts,proto3" json:"opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportVMRequest) Reset() {
	*x = ImportVMRequest{}
	mi := &file_proto_vmmigrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportVMRequest) ProtoMessage() {}

func (x *ImportVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportVMRequest.ProtoReflect.Descriptor instead.
func (*ImportVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{6}
}

func (x *ImportVMRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ImportVMRequest) GetOpts() map[string]string {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ImportVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewVmId       string                 `protobuf:"bytes,1,opt,name=new_vm_id,json=newVmId,proto3" json:"new_vm_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportVMResponse) Reset() {
	*x = ImportVMResponse{}
	mi := &file_proto_vmmigrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportVMResponse) ProtoMessage() {}

func (x *ImportVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportVMResponse.ProtoReflect.Descriptor instead.
func (*ImportVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{7}
}

func (x *ImportVMResponse) GetNewVmId() string {
	if x != nil {
		return x.NewVmId
	}
	return ""
}

func (x *ImportVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartMigrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceProvider string                 `protobuf:"bytes,1,opt,name=source_provider,json=sourceProvider,proto3" json:"source_provider,omitempty"`
	DestProvider   string                 `protobuf:"bytes,2,opt,name=dest_provider,json=destProvider,proto3" json:"dest_provider,omitempty"`
	VmIds          []string               `protobuf:"bytes,3,rep,name=vm_ids,json=vmIds,proto3" json:"vm_ids,omitempty"`
	StagingTarget  string                 `protobuf:"bytes,4,opt,name=staging_target,json=stagingTarget,proto3" json:"staging_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartMigrationRequest) Reset() {
	*x = StartMigrationRequest{}
	mi := &file_proto_vmmigrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationRequest) ProtoMessage() {}

func (x *StartMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationRequest.ProtoReflect.Descriptor instead.
func (*StartMigrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{8}
}

func (x *StartMigrationRequest) GetSourceProvider() string {
	if x != nil {
		return x.SourceProvider
	}
	return ""
}

func (x *StartMigrationRequest) GetDestProvider() string {
	if x != nil {
		return x.DestProvider
	}
	return ""
}

func (x *StartMigrationRequest) GetVmIds() []string {
	if x != nil {
		return x.VmIds
	}
	return nil
}

func (x *StartMigrationRequest) GetStagingTarget() string {
	if x != nil {
		return x.StagingTarget
	}
	return ""
}

type StartMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMigrationResponse) Reset() {
	*x = StartMigrationResponse{}
	mi := &file_proto_vmmigrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationResponse) ProtoMessage() {}

func (x *StartMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationResponse.ProtoReflect.Descriptor instead.
func (*StartMigrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{9}
}

func (x *StartMigrationResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartMigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationRequest) Reset() {
	*x = GetMigrationRequest{}
	mi := &file_proto_vmmigrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationRequest) ProtoMessage() {}

func (x *GetMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{10}
}

func (x *GetMigrationRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type VMProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=vmmigrator.JobState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMProgress) Reset() {
	*x = VMProgress{}
	mi := &file_proto_vmmigrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMProgress) ProtoMessage() {}

func (x *VMProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMProgress.ProtoReflect.Descriptor instead.
func (*VMProgress) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{11}
}

func (x *VMProgress) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMProgress) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_UNKNOWN
}

func (x *VMProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=vmmigrator.JobState" json:"state,omitempty"`
	VmProgress    []*VMProgress          `protobuf:"bytes,3,rep,name=vm_progress,json=vmProgress,proto3" json:"vm_progress,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationResponse) Reset() {
	*x = GetMigrationResponse{}
	mi := &file_proto_vmmigrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationResponse) ProtoMessage() {}

func (x *GetMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vmmigrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_vmmigrator_proto_rawDescGZIP(), []int{12}
}

func (x *GetMigrationResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetMigrationResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_UNKNOWN
}

func (x *GetMigrationResponse) GetVmProgress() []*VMProgress {
	if x != nil {
		return x.VmProgress
	}
	return nil
}

func (x *GetMigrationResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetMigrationResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_proto_vmmigrator_proto protoreflect.FileDescriptor

const file_proto_vmmigrator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/vmmigrator.proto\x12\n" +
	"vmmigrator\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x06VMInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x03R\x03cpu\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x03R\bmemoryMb\x12&\n" +
	"\x05disks\x18\x05 \x03(\v2\x10.vmmigrator.DiskR\x05disks\"M\n" +
	"\x04Disk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\x8f\x01\n" +
	"\x0eListVMsRequest\x12A\n" +
	"\afilters\x18\x01 \x03(\v2'.vmmigrator.ListVMsRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x0fListVMsResponse\x12$\n" +
	"\x03vms\x18\x01 \x03(\v2\x12.vmmigrator.VMInfoR\x03vms\"M\n" +
	"\x0fExportVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12%\n" +
	"\x0estaging_target\x18\x02 \x01(\tR\rstagingTarget\"M\n" +
	"\x10ExportVMResponse\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\x0fImportVMRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x129\n" +
	"\x04opts\x18\x02 \x03(\v2%.vmmigrator.ImportVMRequest.OptsEntryR\x04opts\x1a7\n" +
	"\tOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x10ImportVMResponse\x12\x1a\n" +
	"\tnew_vm_id\x18\x01 \x01(\tR\anewVmId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa3\x01\n" +
	"\x15StartMigrationRequest\x12'\n" +
	"\x0fsource_provider\x18\x01 \x01(\tR\x0esourceProvider\x12#\n" +
	"\rdest_provider\x18\x02 \x01(\tR\fdestProvider\x12\x15\n" +
	"\x06vm_ids\x18\x03 \x03(\tR\x05vmIds\x12%\n" +
	"\x0estaging_target\x18\x04 \x01(\tR\rstagingTarget\"I\n" +
	"\x16StartMigrationResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x13GetMigrationRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"g\n" +
	"\n" +
	"VMProgress\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.vmmigrator.JobStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8a\x02\n" +
	"\x14GetMigrationResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.vmmigrator.JobStateR\x05state\x127\n" +
	"\vvm_progress\x18\x03 \x03(\v2\x16.vmmigrator.VMProgressR\n" +
	"vmProgress\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt*Z\n" +
	"\bJobState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\xe2\x01\n" +
	"\bProvider\x12D\n" +
	"\aListVMs\x12\x1a.vmmigrator.ListVMsRequest\x1a\x1b.vmmigrator.ListVMsResponse\"\x00\x12G\n" +
	"\bExportVM\x12\x1b.vmmigrator.ExportVMRequest\x1a\x1c.vmmigrator.ExportVMResponse\"\x00\x12G\n" +
	"\bImportVM\x12\x1b.vmmigrator.ImportVMRequest\x1a\x1c.vmmigrator.ImportVMResponse\"\x002\xbe\x01\n" +
	"\fOrchestrator\x12Y\n" +
	"\x0eStartMigration\x12!.vmmigrator.StartMigrationRequest\x1a\".vmmigrator.StartMigrationResponse\"\x00\x12S\n" +
	"\fGetMigration\x12\x1f.vmmigrator.GetMigrationRequest\x1a .vmmigrator.GetMigrationResponse\"\x00B\x18Z\x16vmmigrator/proto/proto;protob\x06proto3"

var (
	file_proto_vmmigrator_proto_rawDescOnce sync.Once
	file_proto_vmmigrator_proto_rawDescData []byte
)

func file_proto_vmmigrator_proto_rawDescGZIP() []byte {
	file_proto_vmmigrator_proto_rawDescOnce.Do(func() {
		file_proto_vmmigrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vmmigrator_proto_rawDesc), len(file_proto_vmmigrator_proto_rawDesc)))
	})
	return file_proto_vmmigrator_proto_rawDescData
}

var file_proto_vmmigrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_vmmigrator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_vmmigrator_proto_goTypes = []any{
	(JobState)(0),                  // 0: vmmigrator.JobState
	(*VMInfo)(nil),                 // 1: vmmigrator.VMInfo
	(*Disk)(nil),                   // 2: vmmigrator.Disk
	(*ListVMsRequest)(nil),         // 3: vmmigrator.ListVMsRequest
	(*ListVMsResponse)(nil),        // 4: vmmigrator.ListVMsResponse
	(*ExportVMRequest)(nil),        // 5: vmmigrator.ExportVMRequest
	(*ExportVMResponse)(nil),       // 6: vmmigrator.ExportVMResponse
	(*ImportVMRequest)(nil),        // 7: vmmigrator.ImportVMRequest
	(*ImportVMResponse)(nil),       // 8: vmmigrator.ImportVMResponse
	(*StartMigrationRequest)(nil),  // 9: vmmigrator.StartMigrationRequest
	(*StartMigrationResponse)(nil), // 10: vmmigrator.StartMigrationResponse
	(*GetMigrationRequest)(nil),    // 11: vmmigrator.GetMigrationRequest
	(*VMProgress)(nil),             // 12: vmmigrator.VMProgress
	(*GetMigrationResponse)(nil),   // 13: vmmigrator.GetMigrationResponse
	nil,                            // 14: vmmigrator.ListVMsRequest.FiltersEntry
	nil,                            // 15: vmmigrator.ImportVMRequest.OptsEntry
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_proto_vmmigrator_proto_depIdxs = []int32{
	2,  // 0: vmmigrator.VMInfo.disks:type_name -> vmmigrator.Disk
	14, // 1: vmmigrator.ListVMsRequest.filters:type_name -> vmmigrator.ListVMsRequest.FiltersEntry
	1,  // 2: vmmigrator.ListVMsResponse.vms:type_name -> vmmigrator.VMInfo
	15, // 3: vmmigrator.ImportVMRequest.opts:type_name -> vmmigrator.ImportVMRequest.OptsEntry
	0,  // 4: vmmigrator.VMProgress.state:type_name -> vmmigrator.JobState
	0,  // 5: vmmigrator.GetMigrationResponse.state:type_name -> vmmigrator.JobState
	12, // 6: vmmigrator.GetMigrationResponse.vm_progress:type_name -> vmmigrator.VMProgress
	16, // 7: vmmigrator.GetMigrationResponse.started_at:type_name -> google.protobuf.Timestamp
	16, // 8: vmmigrator.GetMigrationResponse.finished_at:type_name -> google.protobuf.Timestamp
	3,  // 9: vmmigrator.Provider.ListVMs:input_type -> vmmigrator.ListVMsRequest
	5,  // 10: vmmigrator.Provider.ExportVM:input_type -> vmmigrator.ExportVMRequest
	7,  // 11: vmmigrator.Provider.ImportVM:input_type -> vmmigrator.ImportVMRequest
	9,  // 12: vmmigrator.Orchestrator.StartMigration:input_type -> vmmigrator.StartMigrationRequest
	11, // 13: vmmigrator.Orchestrator.GetMigration:input_type -> vmmigrator.GetMigrationRequest
	4,  // 14: vmmigrator.Provider.ListVMs:output_type -> vmmigrator.ListVMsResponse
	6,  // 15: vmmigrator.Provider.ExportVM:output_type -> vmmigrator.ExportVMResponse
	8,  // 16: vmmigrator.Provider.ImportVM:output_type -> vmmigrator.ImportVMResponse
	10, // 17: vmmigrator.Orchestrator.StartMigration:output_type -> vmmigrator.StartMigrationResponse
	13, // 18: vmmigrator.Orchestrator.GetMigration:output_type -> vmmigrator.GetMigrationResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_vmmigrator_proto_init() }
func file_proto_vmmigrator_proto_init() {
	if File_proto_vmmigrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vmmigrator_proto_rawDesc), len(file_proto_vmmigrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_vmmigrator_proto_goTypes,
		DependencyIndexes: file_proto_vmmigrator_proto_depIdxs,
		EnumInfos:         file_proto_vmmigrator_proto_enumTypes,
		MessageInfos:      file_proto_vmmigrator_proto_msgTypes,
	}.Build()
	File_proto_vmmigrator_proto = out.File
	file_proto_vmmigrator_proto_goTypes = nil
	file_proto_vmmigrator_proto_depIdxs = nil
}
